import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import HomeSlider from '@/components/HomeSlider'
import Product from '@/components/Product'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <HomeSlider /> */}
      <main>
        <section class="bg-white py-8">

          <div class="container mx-auto">
            <div className='md:flex'>
              <aside class="sticky top-0 min-w-[300px]">
                <ul>
                  {["Askeri Ayakkabılar", "Bröveler", "Gömlek", "İşbaşı kepi", "İşbaşı",
                    "Kazak", "Kokart", "Rütbeler", "Şerit Rozeti", "Üniformalar"].map((item, i) => (
                      <li className='border-b border-gray-200'>
                        <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">{item}</a>
                      </li>
                    ))}
                </ul>
              </aside>
              <div className='flex items-center flex-wrap pt-4 pb-12'>
                {Array.from({ length: 20 }).map((item, i) => (
                  <Product key={i} />
                ))}
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
