import HomeCategoryList from '@/components/HomeCategoryList'
import Product from '@/components/Product'
import Header from '@/components/header'
import { getProducts } from '@/lib/queries/product'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useMemo } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ products }) {
  console.log(products)
  const router = useRouter()

  const filteredProducts = useMemo(() =>
      products.filter(item => item.category.id == router.query?.category || !router.query?.category),
    [router.query?.category])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <HomeSlider /> */}
      <main>
        <section class="bg-white py-8">

          <div class="container mx-auto">
            <div className='md:flex'>
              <aside class="sticky top-0 min-w-[300px]">
                <HomeCategoryList />
              </aside>
              <div className='flex items-center flex-wrap pt-4 pb-12'>
                {filteredProducts.map((item, i) => (
                  <Product key={i} product={item} />
                ))}
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const products = await getProducts()
  console.log(products)
  return {
    props: {
      products
    },
  }
}
